name: LisaMagid
favicon: null
layout_spectrum: 0.65277
typography_spectrum: 0.46374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1ecf4'
    - '#12232c'
    - '#ffb600'
    - '#696158'
    - '#ff0000'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
