name: LisaMagid
favicon: null
layout_spectrum: 0.65277
typography_spectrum: 0.46374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#24404c'
    - '#fcfcfa'
    - '#a33828'
    - '#5d8a9f'
    - '#9d7224'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: shares
    item: null
    url: null
