name: LisaMagid
favicon: null
layout_spectrum: 0.95759
typography_spectrum: 0.22741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#959595'
    - '#c41f3e'
    - '#064e92'
    - '#29b59f'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 1
purpose:
  - name: shares
    item: null
    url: null
