typography_spectrum: 0.46374
color:
  brandColors:
    - '#0090a0'
    - '#211d4b'
    - '#f94800'
    - '#ffffff'
    - '#aaaaaa'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30145
analytics:
  google: null
  facebook: null
  twitter: null
name: LisaMagid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
