name: LisaMagid
favicon: null
layout_spectrum: 0.30145
typography_spectrum: 0.46374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0090a0'
    - '#211d4b'
    - '#f94800'
    - '#ffffff'
    - '#aaaaaa'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
